/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONVERSION_H_RPCGEN
#define _CONVERSION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int n;
};
typedef struct inputs inputs;

#define CONVERSION_PROG 0x2fffffff
#define CONVERSION_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define DTOBIN 1
extern  int * dtobin_1(inputs *, CLIENT *);
extern  int * dtobin_1_svc(inputs *, struct svc_req *);
extern int conversion_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DTOBIN 1
extern  int * dtobin_1();
extern  int * dtobin_1_svc();
extern int conversion_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONVERSION_H_RPCGEN */
